# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Chef_hire' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Chef_hire





 pod 'Alamofire', '~> 4.7'
 pod 'SVProgressHUD'










  target 'Chef_hireTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Chef_hireUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
